twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Java
    - Kafka
    - Elasticsearch
  welcome-message: Hello Microservices !
  enable-v2-tweets: false
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}

retry-config:
  initialIntervalMs: 1000
  maxIntervalMs: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleepTimeMs: 2000

kafka-config:
  bootstrapServers: localhost:19092, localhost:39092, localhost:39092
  schemaRegistryUrlKey: schema.registry.url
  schemaRegistryUrl: http://localhost:8081
  topicName: twitter-topic
  topicNamesToCreate:
    - twitter-topic
  numOfPartitions: 3
  eplicationFactor: 3

